/*
 * Copyright 2008 Ayman Al-Sairafi ayman.alsairafi@gmail.com
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License
 *       at http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package jsyntaxpane.actions.gui;

import jsyntaxpane.actions.*;
import javax.swing.JOptionPane;
import javax.swing.text.JTextComponent;
import jsyntaxpane.util.SwingUtils;

/**
 * A simple dialog to prompt for a line number and go to it
 * @author Ayman Al-Sairafi
 */
public class GotoLineDialog extends javax.swing.JDialog {

    private static final String PROPERTY_KEY = "GOTOLINE_DIALOG";
    private JTextComponent text;

    /** 
     * Creates new form GotoLineDialog
     * @param text
     */
    private GotoLineDialog(JTextComponent text) {
        super(ActionUtils.getFrameFor(text), false);
        initComponents();
        this.text = text;
        setLocationRelativeTo(text.getRootPane());
        getRootPane().setDefaultButton(jBtnOk);
        text.getDocument().putProperty(PROPERTY_KEY, this);
        SwingUtils.addEscapeListener(this);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCmbLineNumbers = new javax.swing.JComboBox();
        jBtnOk = new javax.swing.JButton();

        setTitle("Goto Line");
        setModal(true);
        setName(""); // NOI18N
        setResizable(false);
        getContentPane().setLayout(new java.awt.FlowLayout());

        jCmbLineNumbers.setEditable(true);
        jCmbLineNumbers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCmbLineNumbersActionPerformed(evt);
            }
        });
        getContentPane().add(jCmbLineNumbers);

        jBtnOk.setAction(jCmbLineNumbers.getAction());
        jBtnOk.setText("Go");
        jBtnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnOkActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnOk);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setTextPos() {
        Object line = jCmbLineNumbers.getSelectedItem();
        if (line != null) {
            try {
                int lineNr = Integer.parseInt(line.toString());
                ActionUtils.insertIntoCombo(jCmbLineNumbers, line);
                ActionUtils.setCaretPosition(text, lineNr, 0);
                setVisible(false);
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "Invalid Number: " + line,
                        "Number Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    private void jCmbLineNumbersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCmbLineNumbersActionPerformed
        if (evt.getActionCommand().equals("comboBoxEdited")) {
            setTextPos();
        }
    }//GEN-LAST:event_jCmbLineNumbersActionPerformed

    private void jBtnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnOkActionPerformed
        setTextPos();
    }//GEN-LAST:event_jBtnOkActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnOk;
    private javax.swing.JComboBox jCmbLineNumbers;
    // End of variables declaration//GEN-END:variables

    /**
     * Create or return the GotoLine dialog for a given ext component
     * @param text
     */
    public static void showForEditor(JTextComponent text) {
        GotoLineDialog dlg = null;
        if ((text == null) || (text.getDocument().getProperty(PROPERTY_KEY) == null)) {
            dlg = new GotoLineDialog(text);
        } else {
            dlg = (GotoLineDialog) text.getDocument().getProperty(PROPERTY_KEY);
        }
        dlg.jCmbLineNumbers.requestFocusInWindow();
        dlg.setVisible(true);
    }
}
